### ISSUE TITLE
Feature Request: Disable some other Worldtypes

### ISSUE THREAD

**Issue by BakermanLP** [djsrv/new-world#1]
Hello,
this is nice in conjunction with your fork of TerrainControl. Just a small feature request here:
- Can you make a kind of blacklist to the config, to disable some worldtypes, like for example amplified, flat and so on?
Thank you

Michael (aka BakermanLP)

**Comment by djsrv** [comment]
Sure, I was planning on making it so buttons can be restricted to certain settings (or locked completely) before officially releasing this.

**Comment by BakermanLP** [comment]
Sorry, I am very early with this :)

**Comment by djsrv** [comment]
Added in 92c2660e707034f7ea1f3cf617b14a53d2bf9f33. :)
